blank_issues_enabled: false
contact_links:
  - name: Jira (Team Members)
    url: https://redhat.atlassian.net/jira/software/projects/HYPERFLEET/boards/1013
    about: HyperFleet team members should create issues in Jira (HYPERFLEET project)
